#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Empty workspace smoke test
on:  [workflow_dispatch]

env:
   USERSTORY: CloneGitRepoAPI
   TS_API_TEST_KUBERNETES_COMMAND_LINE_TOOL: kubectl

jobs:
  smoke-api-tests-on-minikube:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout WTO
      uses: actions/checkout@master
      with:
        repository: devfile/devworkspace-operator
        path: devworkspace-operator

    - name: Checkout tests codebase
      uses: actions/checkout@master
      with:
        repository: eclipse/che
        path: che
    - name: Install NodeJs
      uses: actions/setup-node@v3

    - name: Start minikube cluster
      id: run-minikube
      uses: che-incubator/setup-minikube-action@next
      with:
        minikube-version: v1.23.2

    - name: Setup cert manager
      run: |
        cd devworkspace-operator
        make install_cert_manager
        sleep 360

    - name: Setup DWO
      run: |
        cd devworkspace-operator
        make install

    - name: Pre-pull image on minikube
      run: |
        minikube ssh 'docker pull quay.io/devfile/universal-developer-image:latest'

    - name: Run Empty workspace smoke test
      run: |
        cd che/tests/e2e
        npm i
        npm run driver-less-test




